// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzgqgebityodncxlqbfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16Z3FnZWJpdHlvZG5jeGxxYmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODYwNDgsImV4cCI6MjA3MjU2MjA0OH0.f9BAhNtKFWX5eUaRN27ZX1HFzgkqD6v4nXR7E1qhRXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});